# Read the Docs configuration file for Sphinx projects

# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: windows
  tools:
    python: "3.11"



sphinx:
  configuration: docs/conf.py


python:
  install: "pygame-ce"

